### ISSUE TITLE
[BUG] _reactNative.NativeModules.StarPrinterWrapper.init

### ISSUE THREAD

**Issue by gerome-yocto** [star-micronics/react-native-star-io10#80] opened 2022-09-26 12:57 UTC
## Description
I have an error "null is not an object (evaluating '_reactNative.NativeModules.StarPrinterWrapper.init"

## Your device where the bug occurs 
 - Device: Samsung tab
 - OS: Android 12
 - Version 1.2.0

## Your printer
- Model Names: Star TSP143IIIBi
- Firmware Version:
- Interface: Bluetooth

## Your development environment
The result of executing the command `ver` on Windows, `sw_vers` on macOS, `uname –a` on Linux, or these equivalent commands.

Also, the result of executing the command `npx react-native info`.
info Fetching system and libraries information...
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 96.33 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.2.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.13.0 - /opt/homebrew/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## To Reproduce

I use this command await printer.open(); or await printer.getStatus();

## Additional context
Add any other context about the bug here.

**Comment by gerome-yocto** [comment] 2022-09-28 10:27
anyone help me ? please.

**Comment by gare-bear** [comment] 2022-12-14 09:13
@gerome-yocto please post your code

**Comment by gare-bear** [comment] 2023-02-07 05:56
@gerome-yocto we're you able to find a solution to this issue? 

If you we're not able to find a solution and you still need help with this, please chime in.
As it currently stands, I'm unable to reproduce this issue.

**Comment by can-miki** [comment] 2024-04-26 10:10
@gerome-yocto 
Is there a status update?
We will close the issue once, but if you are still having trouble, please reopen or post a new issue.

**Closed** 2024-04-26 10:10 UTC
Labels: Status: question
