### ISSUE TITLE
 No matching configuration of project :react-native-star-io10 was found.

### ISSUE THREAD

**Issue by avijit-ordering** [star-micronics/react-native-star-io10#102] opened 2023-08-23 05:08 UTC
Hello,

I am facing an issue with this plugin when I want to run. I am getting below error

"No matching configuration of project :react-native-star-io10 was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' but:- None of the consumable configurations have attributes."

I am using the Android Platform.
"react-native-star-io10": "^1.3.0"

## Your development environment
The result of executing the command `npx react-native info`.
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 2.04 GB / 15.65 GB
  Binaries:
    Node: 16.16.0 - c:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - c:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    Visual Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: ^0.64.2 => 0.64.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Expected behavior
Please help me to solve this problem

## Screenshots
![Screenshot_5](https://github.com/star-micronics/react-native-star-io10/assets/16749307/45cc1a19-efa5-4255-8897-c709bd758979)

Thanks

**Comment by can-miki** [comment] 2024-06-07 07:25
We apologize for the late response.
You would like to use the Android platform, but there doesn't seem to be an Android SDK in your environment.

Could you please visit the official [React Native](https://reactnative.dev/docs/set-up-your-environment) website and try building a new project?
If you can create a new project, it means the environment is in order.

And then, please try to import this library to see if the same problem occurs.

**Comment by can-miki** [comment] 2024-12-18 01:15
We will close this issue once, but if the problem is still not resolved, please reopen it or post a new issue.

**Closed by can-miki** 2024-12-18 01:15 UTC
Labels: Status: question, Platform: android
