### ISSUE TITLE
Problems with USB connected printers: "Request timed out" and "Device not found"

### ISSUE THREAD

**Issue by johnbjurulf** [star-micronics/react-native-star-io10#81] opened 2022-10-04 08:13 UTC
## Description
We are experiencing sporadic problems with USB connected printers. The discovery works and we setup a connection to the printer, printing works fine. But then sometimes the printing completely stops working, with the error message: "Request timed out" or "Device not found.". In some cases this can be resolved by running a discovery again `await manager.startDiscovery()` but in some cases the printer is not found anymore. In rare cases the only solution has been to do a factory reset of the ipad we are running the software on.

Would it be possible to get a more detailed description of the error messages we are seeing? ("Request timed out" and "Device not found" in combination with the `Usb` connection type)

## Your device where the bug occurs 
 - Device: 
    iPad Pro 12.9" (5th generation)
 - OS:
    iOS 15.6.1

## Your printer
- Model Names:
    mC-Print3
- Firmware Version:
    3.1
- Interface:
    Usb

## Your development environment
We have only seen this problem in production, but we have not been able to reproduce it in our development environment.

## Additional context
The only implementation difference from the docs you've provided is that we open and close a connection the printer for every print. Built so several devices can use the same printer (for Ethernet that is, so not related to USB).
We have also seen some strange prints in conjunction with these problems, I've attached an image for an example. 
![IMG_2727](https://user-images.githubusercontent.com/3964535/193768588-dc9517aa-4df5-4221-9575-c26abe186eb8.png)

**Comment by bandit-ibayashi** [comment] 2022-10-21 11:57
@johnbjurulf We are afraid we have not been able to respond to this Issue.

I have never received these issues before, so could you please confirm the following points with this user to exclude that the event is not caused by a specific hardware first?

* Does this matter occur on more than one iOS device?
   - I know this happens on an iPad Pro 12.9" (5th gen.), but we would like to check if it also happens on other devices (even different devices of the same model).
* Does the same behaviour occur when using different USB cables?
   - For the same reason as above, we would like to know this information in order to isolate whether this matter is caused by the USB cable itself.

And, it would also be very helpful if this user could provide information on Self-Printing in order to know the model and printer settings.

**Comment by bandit-ibayashi** [comment] 2023-04-26 07:15
This Issue will be closed as there has been no movement for a half of year. If you continue to experience similar issues, please try the following first.
1. Update iOS of your device to the latest version.
2. Update your printer's firmware. Firmware update is available via Star Quick Setup Utility provided by Star Micronics as an iOS app.
3. Update `react-native-star-io10` to the latest version.

If it still does not solve your issue, please post it as a new Issue.

**Closed** 2023-04-26 07:16 UTC
Labels: Status: resolved, Platform: ios, Target: stario10
