### ISSUE TITLE
Invariant: Native Module Cannot be Null (Expo)

### ISSUE THREAD

**Issue by mnm458** [star-micronics/react-native-star-io10#35] opened 2021-12-08 11:08 UTC
Hi there,

I am trying to use this lib for a ios build and when debugging in metro I get the "Native Module Cannot be Null" error (please see screenshot attached). It goes away when I comment the printing code so it is definitely coming from this, I have installed npm package and have listed the package "react-native-star-io10" in my package.json as well but no luck.

I have been trying to solve this for a while, would greatly appreciate any help :)

 
![image](https://user-images.githubusercontent.com/33648499/145198348-72f8bf94-c96e-4d01-a784-fbacb7b0d9d7.png)

**Comment by gare-bear** [comment] 2022-01-18 18:41
I don't think this can run in Expo. Our SDK requires platform-specific features; Bluetooth and BLE to name a few.
I don't think platform specific-code can run in Expo.

**Comment by kickbk** [comment] 2022-01-18 20:51
It should work with an Expo development client.
You probably won't even need a config plugin looking at the install instructions
Most likely just infoPlist/permission settings
It would require some testing of course. Maybe @mnm458 or others have a device and wouldn't mind trying it out?
If there are issues, please share with the Expo community via Discord.
This could be a nice addition to expo.

**Comment by gare-bear** [comment] 2022-05-26 20:45
@kickbk @mnm458 I came across some use info in the React Native [documentation](https://reactnative.dev/docs/environment-setup).

From the Caveats section,
"Because you don't build any native code when using Expo to create a project, it's not possible to include custom native modules beyond the React Native APIs and components that are available in the Expo client app." 

So until that changes from the React Native side, we will not be able to support the Expo client

**Comment by kickbk** [comment] 2022-05-28 18:33
I already created (with the help of the expo team) a fork that works with a custom expo client. I just need to find the time to clean it up and share.
It is highly likely that if you have a project that requires this library, you'd be ok with a custom Expo client. You'd be handling native via a config plugin.

**Comment by felipesoares6** [comment] 2022-08-03 18:11
Hey @kickbk I think I'm having the same issue, could you please share this fork?

**Comment by jongbelegen** [comment] 2022-10-24 15:33
@felipesoares6 looks like this is the fork:
https://github.com/star-micronics/react-native-star-io10/compare/master...kickbk:react-native-star-io10:master

**Comment by jongbelegen** [comment] 2022-11-01 15:27
I made a fork that contains some of these fixes, you can try them out by using:
```
"react-native-star-io10": "https://github.com/jongbelegen/react-native-star-io10",
``` 
In your package.json

**Comment by bandit-ibayashi** [comment] 2023-12-12 02:19
I have posted a workaround that we think is relevant to this issue at [Issue #90](https://github.com/star-micronics/react-native-star-io10/issues/90#issuecomment-1846849105).
We would appreciate it if you could refer to this.

**Comment by can-miki** [comment] 2024-05-07 10:18
Have you found a solution to this problem?
We will close this issue once, but if the issue is still not resolved, please reopen it or post a new issue.

**Closed by can-miki** 2024-05-07 10:18 UTC
