### ISSUE TITLE
Print command not working, Invalid resource

### ISSUE THREAD

**Issue by prashant828** [star-micronics/react-native-star-io10#40] opened 2022-01-09 04:19 UTC
I can see the printer after discovery, but after making print command. it does not do anything and console prints an error

Error: Invalid resource

**Comment by Frankiz123** [comment] 2022-02-03 17:42
@prashant828  did you find solution?

**Comment by kickbk** [comment] 2022-02-03 18:15
Did you try to comment out images in your print? I think there's an issue with fetching images for print. Got the same error. When you comment out the image from the print makes it work. Tried relative path to the image in different ways but still no go.

**Comment by Frankiz123** [comment] 2022-02-03 18:16
ok
thanks let me check @kickbk

**Comment by Frankiz123** [comment] 2022-02-03 18:20
@kickbk my android app is not running after installing star io

**Comment by kickbk** [comment] 2022-02-03 18:26
I'm not sure what's going on. I'm not one of the maintainers, so you'll need to check with them. But I recommend you share many more details on what is not working when you try to run it.

**Comment by Frankiz123** [comment] 2022-02-03 19:03
@kickbk  check this
<img width="1280" alt="Screenshot 2022-02-04 at 12 02 35 AM" src="https://user-images.githubusercontent.com/17431855/152411099-afcd1aee-b641-42be-9236-5577ddde93ca.png">

**Comment by can-miki** [comment] 2024-05-23 04:32
Could you take a look at our bug report template and provide all the information we require?
We want to help you but we need all that information in order to do so.

Also, it looks like your issue is with the the react-native library and not related to react-native-star-io10.

**Comment by can-miki** [comment] 2024-12-18 01:13
We will close this issue once, but if the problem is still not resolved, please reopen it or post a new issue.

**Closed by can-miki** 2024-12-18 01:13 UTC
Labels: Status: question
